version: "3.8"

services:
  redis:
    image: redis:6.2.0
  api:
    restart: always
    build:
      context: ./packages/api
    depends_on:
      - redis
  app:
    build:
      context: ./packages/dashboards
    depends_on:
      - api
