version: '3.8'

services:
  redis:
    container_name: ecommerce-analytics_redis_staging
    ports:
      - 8001:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped
  api:
    container_name: ecommerce-analytics_api_staging
    ports:
      - 8002:4000
    environment:
      - DB_URL=http://localhost:8000
      - REDIS_URL=redis://redis:6379
    build:
      dockerfile: ./Dockerfile
    env_file:
      - './packages/api/.env'
    volumes:
      - ./packages/api:/api
      - /api/node_modules
      - /api/dist
    restart: unless-stopped
  app:
    container_name: ecommerce-analytics_app_staging
    ports:
      - 8003:3000
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./packages/dashboards:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    restart: unless-stopped

volumes:
  redis_data:
